num_classes =  {
'bile': 3,
'materiel_endobiliaire': 4,
'lesion_post_stent': 2,
'atteinte_circonferentielle': 2,
'stenose_multi': 2, 
'debut_stenose': 3,
'infiltration_stenose': 2,
'reduction_lumiere': 3, 
'ulceration': 2,
'ulceration_multi': 2,
'ulceration_creusante': 2,
'ulceration_irreg': 2,
'polypoid_pattern': 3,
'villous_pattern': 3,
'regularite_relief': 2,
'type_relief': 3,
'saignement': 2,
'vaisseaux_irrreguliers': 2,
'dilatation_vaisseaux': 2,
'couleur': 4,
'diagnostique': 2,
'diagnostique_neoplasie': 3,
'video': 3
}